language: cpp
sudo: false
cache:
  directories:
  - container
env:
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1"
- CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest"
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0"
- CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0"
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage"
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py | python /dev/stdin -d container -s setup/bii/setup.py -e bash -p /dev/stdout --cmake-version ${CMAKE_VERSION})
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]] ; then container/_languages/python/3.4.1/bin/psq-travis-container-exec --distro Ubuntu --release precise container/_languages/os/Ubuntu.precise.None --show-output -- ln -sf /usr/bin/clang-tidy-3.6 /usr/bin/clang-tidy ; fi
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]] ; then container/_languages/python/3.4.2/bin/psq-travis-container-exec --distro OSX --release precise container/_languages/os/OSX.10.10.None --show-output -- brew link llvm --force ; fi
script:
- polysquare_run check/bii/check.py ${COVERAGE} --cmake-namespace "clang_tidy" --generator "${CMAKE_GENERATOR}" --block "smspillaz/clang-tidy-target-cmake"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/bii/coverage.py
before_deploy:
- polysquare_run deploy/bii/deploy.py
deploy:
  provider: biicode
  skip_cleanup: true
  user:
    secure: J5JPMuxENUqUJf6AKPiY1MdO9xAlXGwhLkGyGwceQWHZ42yqvC9kaRxwSPGVD964qi4/KGADx+pOZpUyTiJQXp8bS4vir6RzPTtVbS4yhtZYvgI5oWi9/3DNxAwqVwBTb7Jw81EWV4ahG53zpqgBTrdb16zT8xsKZz3WoUOfmT4=
  password:
    secure: A5WtjsL19sYMgoPackDoMWpHZZByUX/Kkm9CVwa6uTs7HzVBiMi6Yo9maRES1sqIFN3w0v8M+t3s/B5EDtR7Kygc5tmMJ55jzQEPkqvPkEcDYdfkMyFSHEX06UvwueLBvU1gRLdioyMxdWEM1h4n68jFg4NAmCqFanoyeiw/gUg=
  on:
    repo: polysquare/clang-tidy-target-cmake
    branch: master
    condition: ${DEPLOY} = 1
